n1 = float(input('Digite um numero:'))
n2 = float(input('Digite outro numero:'))
soma = n1 + n2
subtracao = n1 - n2
multiplicacao = n1 * n2
divisao = n1 / n2
print('soma =',soma)
print('subtracao =',subtracao)
print('multiplicacao =',multiplicacao)
print('divisao =',divisao)